### ISSUE TITLE
Receiving IO error when trying to run the example.py using Raspberry Pi B+

### ISSUE THREAD

**Issue by cjbuchmann** [adafruit/Adafruit_Python_MCP9808#1]
Hey!

I'm running into an issue when trying to run the example.py. I get the following error

```
pi@raspberrypi ~/servos $ sudo python MCP9808_example.py 
Traceback (most recent call last):
  File "MCP9808_example.py", line 44, in <module>
    sensor = MCP9808.MCP9808()
  File "build/bdist.linux-armv6l/egg/Adafruit_MCP9808/MCP9808.py", line 64, in __init__
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 66, in get_i2c_device
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 95, in __init__
IOError: [Errno 2] No such file or directory
```

For a little debug info for the Adafruit_GPIO library, here's my platform info :

```
pi@raspberrypi ~/servos $ python
Python 2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Adafruit_GPIO.Platform as Platform
>>> Platform.platform_detect()
1
>>> Platform.pi_revision()
2
>>> 
```

My setup is documented below :

![20151208_233919](https://cloud.githubusercontent.com/assets/526429/11679480/4c23a83e-9e06-11e5-919b-832b78b26d27.jpg)
![20151208_233908](https://cloud.githubusercontent.com/assets/526429/11679481/4c24185a-9e06-11e5-8413-f38b17808039.jpg)
![20151208_233858](https://cloud.githubusercontent.com/assets/526429/11679482/4c27a1f0-9e06-11e5-9d51-63656197b40b.jpg)
![20151208_233844](https://cloud.githubusercontent.com/assets/526429/11679483/4c27be60-9e06-11e5-80ce-b93e15e728ff.jpg)

**Comment by tdicola** [comment]
IO error usually means the I2C bus hasn't been enabled yet because it can't find the /dev/i2c-1 device.  Check out this guide page to see how to enable it with raspi-config and some small setting updates:  https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c  Then use the i2cdetect command to make sure you can see the device at its default address (0x18).
