### ISSUE TITLE
Following guide breaks YouTube on Raspbian Jessie on pi 3

### ISSUE THREAD

**Issue by joeynuggetz** [adafruit/Adafruit_Python_MCP9808#2]
Would there be any relation to installing the packages listed in the MCP9808 rasp pi guide and youtube failing to play videos? Youtube has been working all morning and the only thing I've done is follow the guide to get the libraries installed for the sensor and now youtube no longer functions.

**Comment by joeynuggetz** [comment]
Forgot to mention this is with the default Epiphany browser

**Comment by tdicola** [comment]
No that shouldn't be related to youtube videos and the browser on Raspbian.  This library just works with Python and installs itself in Python's site-packages folder.  For youtube, videos, web browsers etc. they have their own state that's outside of Python.  You might try starting fresh with the latest version of Raspbian, good luck!
